// Generated by CoffeeScript 1.12.7
var OPAnalyticsData;

OPAnalyticsData = (function() {
  function OPAnalyticsData(url1, browserWidth, browserHeight, action) {
    this.url = url1;
    this.browserWidth = browserWidth;
    this.browserHeight = browserHeight;
    this.action = action;
    this.domain = this._extractUrlDomain(this.url);
    this.userAgent = navigator.userAgent;
    this.screenSize = screen.width + "x" + screen.height;
  }

  OPAnalyticsData.prototype._extractUrlDomain = function(url) {
    var tmp;
    tmp = document.createElement('a');
    tmp.href = url;
    return psl.parse(tmp.hostname).domain;
  };

  return OPAnalyticsData;

})();
