// Generated by CoffeeScript 1.12.7

/**
@license Copyright (C) 2012 Observepoint LLC. All rights reserved.
 */
chrome.devtools.panels.create("ObservePoint", "img/icon.png", "panel.html", function(extensionPanel) {
  var bgconn, clearContentButton, connId, exportButton, panel, toggleClearButton;
  console.log('1. panel creation callback started');
  panel = extensionPanel;
  connId = chrome.devtools.inspectedWindow.tabId + 'devtools';
  bgconn = chrome.extension.connect({
    name: 'observepoint-' + connId
  });
  extensionPanel.onShown.addListener(function(window) {
    console.log('3. observepoint tab shown');
    panel.windowObj = window;

    /**
     * Update extension theme with defined DevTools theme
     */
    window.switchTheme(chrome.devtools.panels.themeName);

    /**
     * Send startDataLayerHandler message to `js/background.js`
     */
    return bgconn.postMessage({
      action: 'startDataLayerHandler',
      tabId: chrome.devtools.inspectedWindow.tabId
    });
  });
  toggleClearButton = panel.createStatusBarButton("img/toggleClearButton1.png", "Clearing tags on navigation", false);
  toggleClearButton.onClicked.addListener(function() {
    if (panel.windowObj.getClearOnNavigate()) {
      panel.windowObj.setClearOnNavigate(false);
      toggleClearButton.update("img/toggleClearButton2.png", "Tags persist through navigation", false);
      panel.windowObj.clearContent = panel.windowObj.clearContentOff;
      return bgconn.postMessage({
        action: "analytics",
        actionName: "persistency",
        tabId: chrome.devtools.inspectedWindow.tabId
      });
    } else {
      panel.windowObj.setClearOnNavigate(true);
      toggleClearButton.update("img/toggleClearButton1.png", "Clearing tags on navigation", false);
      return panel.windowObj.clearContent = panel.windowObj.clearContentDefault;
    }
  });
  clearContentButton = panel.createStatusBarButton("img/clearContentButton.png", "Clear tag requests", false);
  clearContentButton.onClicked.addListener(function() {
    panel.windowObj.clearContentDefault();
    return bgconn.postMessage({
      action: "analytics",
      actionName: "Clear Tag Request",
      tabId: chrome.devtools.inspectedWindow.tabId
    });
  });
  exportButton = panel.createStatusBarButton("img/download.png", "Export data", false);
  return exportButton.onClicked.addListener(function() {
    return panel.windowObj.exportContent();
  });
});
