// Generated by CoffeeScript 1.12.7
var HttpClient;

HttpClient = (function() {
  function HttpClient() {}

  HttpClient.prototype.get = function(url, callback) {
    var req;
    req = new XMLHttpRequest();
    req.onreadystatechange = function() {
      if (callback && req.readyState === 4 && req.status === 200) {
        return callback(req.responseText);
      }
    };
    req.open("GET", url, true);
    return req.send(null);
  };

  return HttpClient;

})();
