// Generated by CoffeeScript 1.12.7
var restore_options, save_options;

save_options = function() {
  var datalayer_objects, error;
  try {
    datalayer_objects = $("#datalayer").val().trim();
    return chrome.storage.local.set({
      datalayer_objects: datalayer_objects
    }, function(stored) {
      $("#save_message").show();
      return $("#save_message").html("Saved").stop().fadeOut(1000);
    });
  } catch (error1) {
    error = error1;
    return $("#save_message").html("Error while saving: " + error);
  }
};

restore_options = function() {
  return chrome.storage.local.get({
    datalayer_objects: ''
  }, function(stored) {
    return $("#datalayer").val(stored.datalayer_objects);
  });
};

document.addEventListener('DOMContentLoaded', restore_options);

document.querySelector('#save').addEventListener('click', save_options);
