(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';const m=Array.from("\ud83d\udc35\ud83d\udc21\ud83d\udc36\ud83d\udc28\ud83d\udc38\ud83e\udd8a\ud83d\udc37\ud83d\udc22\ud83d\udc31\ud83d\udc26\ud83d\udc2f\ud83d\udc34\ud83e\udd8b\ud83d\udc2e\ud83d\udc2d\ud83e\udd84\ud83d\udc30\ud83d\udc3c\ud83d\udc24\ud83d\udc39\ud83d\udc32\ud83d\udc1f\ud83e\udd81\ud83d\udc19\ud83e\udd82\ud83e\udd80"),n=Array.from("\ud83d\udd37\ud83d\udfe5\ud83d\udfe1\ud83d\udfe9\ud83d\udd35\u2b55\ud83d\udd36\ud83d\udfe2\ud83d\udfe6\ud83d\udd34\ud83d\udfe8");
n.push(m[Math.floor(Math.random()*m.length)]);
var t=function(b,c){var a,f;const h=null===(f=null===(a=c.sender)||void 0===a?void 0:a.tab)||void 0===f?void 0:f.id;if(null!=h){b.b.tabs.update(h,{autoDiscardable:!1});var g=b.c.get(h);null!=g?g.port=c:(g={port:c,g:new Set},b.c.set(h,g));c.onMessage.addListener(k=>{if("CONTAINER_DETAILS"===k.data.type){const e=k.data.data.nonce,d=b.i.get(e);b.i.delete(e);p(k,d)}else g.g.forEach(e=>{var d;null===(d=b.a.get(e))||void 0===d?void 0:d.frames.forEach(l=>{p(k,l)})})});c.onDisconnect.addListener(()=>{g.port=
void 0})}},w=function(b,c){var a,f,h;const g=null===(f=null===(a=c.sender)||void 0===a?void 0:a.tab)||void 0===f?void 0:f.id,k=null===(h=c.sender)||void 0===h?void 0:h.frameId;if(null!=g&&null!=k){b.b.tabs.update(g,{autoDiscardable:!1});var e=b.a.get(g);null==e&&(e=u(void 0),b.a.set(g,e));var d=e.frames.get(k);null!=d?d.port=c:(d=v(b,c),e.frames.set(k,d));c.onMessage.addListener(l=>{var q,r;null!=e.f&&("CONTAINER_STARTING"===l.data.type&&b.i.set(l.data.data.nonce,d),l.data.emoji=d.emoji,l.source=
"EXTENSION",null===(r=null===(q=b.c.get(e.f))||void 0===q?void 0:q.port)||void 0===r?void 0:r.postMessage(l))});c.onDisconnect.addListener(()=>{d.port=void 0})}},x=function(b,c,a=0){b.b.tabs.executeScript(c,{file:"api/content_script_bin.js",runAt:"document_start",allFrames:!0,frameId:a})},p=function(b,c){null!==c&&void 0!==c&&c.port&&(b.data.emoji=c.emoji,b.source="EXTENSION",c.port.postMessage(b))},u=function(b){return{f:b,frames:new Map}},v=function(b,c){c={port:c,emoji:n[b.h]};b.h++;b.h>=n.length&&
(b.h=0);return c};new class{constructor(){this.b=chrome;this.c=new Map;this.a=new Map;this.h=0;this.i=new Map;this.b.runtime.onConnectExternal.addListener(b=>{"TAG_ASSISTANT_EXTENSION_PORT"===b.name&&t(this,b)});this.b.runtime.onConnect.addListener(b=>{w(this,b)});this.b.webNavigation.onCreatedNavigationTarget.addListener(({tabId:b,sourceTabId:c,url:a})=>{a=new URL(a);a.hostname.endsWith(".google.com")&&null!=a.searchParams.get("restart_tag_assistant")?(this.c.has(c)||((a=this.a.get(c))?(a.f=b,0===a.frames.size?x(this,
c):(a=a.frames.get(0),(null===a||void 0===a?0:a.port)||x(this,c))):(this.a.set(c,u(b)),x(this,c)),(a=this.c.get(b))?a.g.add(c):this.c.set(b,{g:new Set([c])})),a=!0):a=!1;if(a=!a)a=this.c.get(c),null!==a&&void 0!==a&&a.port?(a.g.add(b),(a=this.a.get(b))?a.f=c:(this.a.set(b,u(c)),x(this,b)),a=!0):a=!1,a=!a;if(a){var f;if(a=this.a.get(c))c=this.a.get(b),a=a.f,c?c.f=a:(this.a.set(b,u(a)),x(this,b)),null!=a&&(null===(f=this.c.get(a))||void 0===f?void 0:f.g.add(b))}});this.b.webNavigation.onCommitted.addListener(({tabId:b,
frameId:c,url:a})=>{"https://tagassistant.google.com"!==(new URL(a)).origin&&this.a.has(b)&&x(this,b,c)});this.b.runtime.onMessageExternal.addListener((b,c,a)=>{a({})})}};}).call(this);
