(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k=this||self,l=/^[\w+/_-]+[=]{0,2}$/,m=null,n=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&l.test(a)?a:""},p=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},q=function(a,b){function e(){}e.prototype=b.prototype;a.h=b.prototype;a.prototype=new e;a.prototype.constructor=a;a.g=function(h,f,g){for(var d=Array(arguments.length-2),c=2;c<arguments.length;c++)d[c-2]=arguments[c];return b.prototype[f].apply(h,
d)}},r=function(a){return a};function t(a){if(Error.captureStackTrace)Error.captureStackTrace(this,t);else{const b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(t,Error);t.prototype.name="CustomError";var u=function(a,b){a=a.split("%s");for(var e="",h=a.length-1,f=0;f<h;f++)e+=a[f]+(f<b.length?b[f]:"%s");t.call(this,e+a[h])};q(u,t);u.prototype.name="AssertionError";
var v=function(a,b,e,h){var f="Assertion failed";if(e){f+=": "+e;var g=h}else a&&(f+=": "+a,g=b);throw new u(""+f,g||[]);},w=function(a,b,e){a||v("",null,b,Array.prototype.slice.call(arguments,2))},y=function(a,b){throw new u("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},z=function(a,b,e){"string"!==typeof a&&v("Expected string but got %s: %s.",[p(a),a],b,Array.prototype.slice.call(arguments,2))};var A;var D=function(a,b){this.b=a===B&&b||"";this.c=C};D.prototype.toString=function(){return"Const{"+this.b+"}"};var E=function(a){if(a instanceof D&&a.constructor===D&&a.c===C)return a.b;y("expected object of type Const, got '"+a+"'");return"type_error:Const"},C={},B={};var G=class{constructor(a,b){this.a=b===F?a:""}};G.prototype.toString=function(){return"TrustedResourceUrl{"+this.a+"}"};var F={};(class{constructor(a,b){this.f=b===H?a:""}}).prototype.toString=function(){return"SafeStyle{"+this.f+"}"};var H={};const I=new D(B,"Resource is Const encoded with chrome.runtime.getURL(\u2026).");var K=function(a){var b=E(J);b=chrome.runtime.getURL(b);z(E(I),"must provide justification");var e=E(I);w(!/^[\s\xa0]*$/.test(e),"must provide non-empty justification");if(void 0===A){e=null;var h=k.trustedTypes;if(h&&h.createPolicy)try{e=h.createPolicy("goog#html",{createHTML:r,createScript:r,createScriptURL:r})}catch(x){k.console&&k.console.error(x.message)}A=e}b=(e=A)?e.createScriptURL(b):b;b=new G(b,F);a:{try{var f=a&&a.ownerDocument,g=f&&(f.defaultView||f.parentWindow);g=g||k;if(g.Element&&g.Location){var d=
g;break a}}catch(x){}d=null}if(d&&"undefined"!=typeof d.HTMLScriptElement&&(!a||!(a instanceof d.HTMLScriptElement)&&(a instanceof d.Location||a instanceof d.Element))){d=typeof a;if("object"==d&&null!=a||"function"==d)try{var c=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(x){c="<object could not be stringified>"}else c=void 0===a?"undefined":null===a?"null":typeof a;y("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLScriptElement",
c)}b instanceof G&&b.constructor===G?c=b.a:(y("expected object of type TrustedResourceUrl, got '"+b+"' of type "+p(b)),c="type_error:TrustedResourceUrl");a.src=c;(c=a.ownerDocument&&a.ownerDocument.defaultView)&&c!=k?c=n(c.document):(null===m&&(m=n(k.document)),c=m);c&&a.setAttribute("nonce",c)};const J=new D(B,"api/tag_assistant_api_bin.js");(function(a,b,e){const h=e.createElement("script");K(h);e.documentElement.appendChild(h);const f=a.runtime.connect();f.onMessage.addListener(g=>{b.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:g}))});b.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",g=>{var d=g.detail;a:{var c=null===d||void 0===d?void 0:d.type;if("string"!==typeof c)c=!1;else switch(c){case "PIPE_MESSAGE":case "DISCONNECT":c=!0;break a;default:c=!1}}if(c)a:if(d=null===d||void 0===d?void 0:d.source,
"string"!==typeof d)c=!1;else switch(d){case "PAGE":case "EXTENSION":c=!0;break a;default:c=!1}if(c&&(g=g.detail,"PAGE"===g.source))switch(g.type){case "PIPE_MESSAGE":g.origin=b.origin;f.postMessage(g);break;case "DISCONNECT":f.disconnect()}})})(chrome,window,document);}).call(this);
