/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},v=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ba=function(a){if(!(a instanceof Array)){a=v(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},da=function(a){a=
["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},y=da(this),z=function(a,b){if(b)a:{var c=y;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}},ha="function"==typeof Object.assign?
Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};z("Object.assign",function(a){return a||ha});
z("Promise",function(a){function b(){this.B=null}function c(f){return f instanceof e?f:new e(function(h){h(f)})}if(a)return a;b.prototype.W=function(f){if(null==this.B){this.B=[];var h=this;this.X(function(){h.da()})}this.B.push(f)};var d=y.setTimeout;b.prototype.X=function(f){d(f,0)};b.prototype.da=function(){for(;this.B&&this.B.length;){var f=this.B;this.B=[];for(var h=0;h<f.length;++h){var n=f[h];f[h]=null;try{n()}catch(r){this.ba(r)}}}this.B=null};b.prototype.ba=function(f){this.X(function(){throw f;
})};var e=function(f){this.N=0;this.P=void 0;this.L=[];this.Z=!1;var h=this.T();try{f(h.resolve,h.reject)}catch(n){h.reject(n)}};e.prototype.T=function(){function f(r){return function(w){n||(n=!0,r.call(h,w))}}var h=this,n=!1;return{resolve:f(this.ia),reject:f(this.U)}};e.prototype.ia=function(f){if(f===this)this.U(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof e)this.ka(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=
!1}h?this.ha(f):this.Y(f)}};e.prototype.ha=function(f){var h=void 0;try{h=f.then}catch(n){this.U(n);return}"function"==typeof h?this.la(h,f):this.Y(f)};e.prototype.U=function(f){this.$(2,f)};e.prototype.Y=function(f){this.$(1,f)};e.prototype.$=function(f,h){if(0!=this.N)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.N);this.N=f;this.P=h;2===this.N&&this.ja();this.ea()};e.prototype.ja=function(){var f=this;d(function(){if(f.ga()){var h=y.console;"undefined"!==typeof h&&
h.error(f.P)}},1)};e.prototype.ga=function(){if(this.Z)return!1;var f=y.CustomEvent,h=y.Event,n=y.dispatchEvent;if("undefined"===typeof n)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=y.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.P;return n(f)};e.prototype.ea=function(){if(null!=this.L){for(var f=0;f<this.L.length;++f)k.W(this.L[f]);
this.L=null}};var k=new b;e.prototype.ka=function(f){var h=this.T();f.S(h.resolve,h.reject)};e.prototype.la=function(f,h){var n=this.T();try{f.call(h,n.resolve,n.reject)}catch(r){n.reject(r)}};e.prototype.then=function(f,h){function n(x,g){return"function"==typeof x?function(m){try{r(x(m))}catch(p){w(p)}}:g}var r,w,G=new e(function(x,g){r=x;w=g});this.S(n(f,r),n(h,w));return G};e.prototype.catch=function(f){return this.then(void 0,f)};e.prototype.S=function(f,h){function n(){switch(r.N){case 1:f(r.P);
break;case 2:h(r.P);break;default:throw Error("Unexpected state: "+r.N);}}var r=this;null==this.L?k.W(n):this.L.push(n);this.Z=!0};e.resolve=c;e.reject=function(f){return new e(function(h,n){n(f)})};e.race=function(f){return new e(function(h,n){for(var r=v(f),w=r.next();!w.done;w=r.next())c(w.value).S(h,n)})};e.all=function(f){var h=v(f),n=h.next();return n.done?c([]):new e(function(r,w){function G(m){return function(p){x[m]=p;g--;0==g&&r(x)}}var x=[],g=0;do x.push(void 0),g++,c(n.value).S(G(x.length-
1),w),n=h.next();while(!n.done)})};return e});z("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});
var ia=this||self,ja=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},A=function(a){var b=ja(a);return"array"==b||"object"==b&&"number"==typeof a.length},ka=function(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ma=function(d,e,k){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}};var B={},C=(B.galaxy_s8={A:360,u:740,v:3,o:"Mozilla/5.0 (Linux; Android 7.0; SM-G950U Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36",H:"Mobile",G:"Galaxy S8",F:"opt_device_mobile_blk"},B.galaxy_note8={A:412,u:846,v:3.5,o:"Mozilla/5.0 (Linux; Android 7.1.1; SAMSUNG SM-N950U Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36",H:"Mobile",G:"Galaxy Note 8",F:"opt_device_mobile_blk"},B.galaxy_tab=
{A:768,u:1024,v:2,o:"Mozilla/5.0 (Linux; Android 7.0; SM-T827V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36",H:"Tablet",G:"Galaxy Tab",F:"opt_device_tablet_blk"},B.iphone_7={A:375,u:667,v:2,o:"Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/11.0 Mobile/14E304 Safari/604.1",H:"Mobile",G:"iPhone 7",F:"opt_device_mobile_blk"},B.iphone_7_plus={A:414,u:736,v:3,o:"Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B150 Safari/604.1",
H:"Mobile",G:"iPhone 7 plus",F:"opt_device_mobile_blk"},B.iphone_x={A:375,u:812,v:3,o:"Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1",H:"Mobile",G:"iPhone X",F:"opt_device_mobile_blk"},B.ipad={A:768,u:1024,v:2,o:"Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1",H:"Tablet",G:"iPad",F:"opt_device_tablet_blk"},B.responsive={A:768,u:474,
v:1,o:"",H:"Responsive",G:"Responsive",F:"opt_device_web_blk"},B);C.mobile=C.iphone_7;C.tablet=C.ipad;var la=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function ma(a){return a?(a=a.match(la))?a[3]||null:null:null};var na=function(a,b){this.webRequest=chrome.webRequest;this.storage=a;this.ca=b},pa=function(a,b){a.g&&a.webRequest.onBeforeRequest.removeListener(a.g);a.g=oa(a,b);a.webRequest.onBeforeRequest.addListener(a.g,{types:["script"],urls:["*://*/*optimize.js*","*://*/*gtm/js*"],tabId:b.tabId},["blocking"])},D=function(a){a.g&&a.webRequest.onBeforeRequest.removeListener(a.g);a.g=void 0},oa=function(a,b){return function(c){if(144E5<=a.ca()-b.startTimeMs)a.storage.remove(["containerParams"]),D(a);else if(c.url&&
(-1!==c.url.indexOf("/gtm/js?id="+b.containerPublicId)||-1!==c.url.indexOf("/optimize.js?id="+b.containerPublicId))){var d="";b.resourceKey&&(d+="&gtm_preview="+encodeURIComponent(b.resourceKey));b.auth&&(d+="&gtm_auth="+encodeURIComponent(b.auth));b.experiment&&(d+="&gtm_experiment="+encodeURIComponent(b.experiment));b.debug&&(d+="&gtm_debug="+b.debug);if(-1===c.url.indexOf(d))return{redirectUrl:c.url+d}}}};var qa=function(a,b,c){if(a.runtime.lastError)alert(a.i18n.getMessage("emulation_failure",[a.runtime.lastError.message]));else{var d={tabId:b},e=C[c];a.I.attach(d,"1.1",function(){a.I.sendCommand(d,"Network.enable");a.I.sendCommand(d,"Page.enable");a.I.sendCommand(d,"Page.setTouchEmulationEnabled",{enabled:!0});a.I.sendCommand(d,"Page.setDeviceMetricsOverride",{width:e.A,height:e.u,deviceScaleFactor:e.v,mobile:!0,fitWindow:!0});a.I.sendCommand(d,"Network.setUserAgentOverride",{userAgent:e.o});a.I.sendCommand(d,
"Page.reload",{})})}},ua=function(a,b,c){ra(a);c&&(a.g=sa(c),a.g&&a.webRequest.onBeforeSendHeaders.addListener(a.g,{urls:["<all_urls>"],tabId:b},["blocking","requestHeaders"]))},ra=function(a){a.g&&a.webRequest.onBeforeSendHeaders.removeListener(a.g);a.g=null};
function sa(a){a=C[a];if(!a)return null;var b=a.o;return b?function(c){if(c.requestHeaders){for(var d=0;d<c.requestHeaders.length;++d){var e=c.requestHeaders[d];if("user-agent"===e.name.toLowerCase()){e.value=b;break}}return{requestHeaders:c.requestHeaders}}}:null};var E=function(){var a=chrome.runtime;this.storage=chrome.storage.local;this.runtime=a};E.prototype.clear=function(){var a=this;return F(this,function(b){return void a.storage.clear(b)})};E.prototype.set=function(a){var b=this;return F(this,function(c){return void b.storage.set(a,c)})};E.prototype.remove=function(a){var b=this;return F(this,function(c){return void b.storage.remove(a,c)})};
E.prototype.get=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;return F(this,function(e){return void d.storage.get(b,e)})};var F=function(a,b){return(new Promise(b)).then(function(c){if(a.runtime.lastError)throw a.runtime.lastError;return c})};function H(a){if(Error.captureStackTrace)Error.captureStackTrace(this,H);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}ka(H,Error);H.prototype.name="CustomError";var I=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");H.call(this,c+a[d])};ka(I,H);I.prototype.name="AssertionError";var va=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var k=d}else a&&(e+=": "+a,k=b);throw new I(""+e,k||[]);},wa=function(a,b,c){a||va("",null,b,Array.prototype.slice.call(arguments,2))},J=function(a,b,c){"number"!==typeof a&&va("Expected number but got %s: %s.",[ja(a),a],b,Array.prototype.slice.call(arguments,2));return a};var xa=Array.prototype.forEach?function(a,b,c){wa(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,k=0;k<d;k++)k in e&&b.call(c,e[k],k,a)};function ya(a){return Array.prototype.concat.apply([],arguments)}function za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Aa="StopIteration"in ia?ia.StopIteration:{message:"StopIteration",stack:""},Ba=function(){};Ba.prototype.next=function(){throw Aa;};Ba.prototype.aa=function(){return this};var K=function(a,b){this.j={};this.c=[];this.R=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};q=K.prototype;q.m=function(){L(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};q.C=function(){L(this);return this.c.concat()};q.O=function(a){return M(this.j,a)};q.clear=function(){this.j={};this.R=this.b=this.c.length=0};
q.remove=function(a){return M(this.j,a)?(delete this.j[a],this.b--,this.R++,this.c.length>2*this.b&&L(this),!0):!1};var L=function(a){if(a.b!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];M(a.j,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.b!=a.c.length){var e={};for(c=b=0;b<a.c.length;)d=a.c[b],M(e,d)||(a.c[c++]=d,e[d]=1),b++;a.c.length=c}};q=K.prototype;q.get=function(a,b){return M(this.j,a)?this.j[a]:b};q.set=function(a,b){M(this.j,a)||(this.b++,this.c.push(a),this.R++);this.j[a]=b};
q.addAll=function(a){if(a instanceof K)for(var b=a.C(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};q.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],k=this.get(e);a.call(b,k,e,this)}};q.clone=function(){return new K(this)};q.aa=function(a){L(this);var b=0,c=this.R,d=this,e=new Ba;e.next=function(){if(c!=d.R)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw Aa;var k=d.c[b++];return a?k:d.j[k]};return e};
var M=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Ca=function(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(A(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Da=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(A(a)||"string"===typeof a)xa(a,b,c);else{if(a.C&&"function"==typeof a.C)var d=a.C();else if(a.m&&"function"==typeof a.m)d=void 0;else if(A(a)||"string"===typeof a){d=[];for(var e=a.length,k=0;k<e;k++)d.push(k)}else for(k in d=
[],e=0,a)d[e++]=k;e=Ca(a);k=e.length;for(var f=0;f<k;f++)b.call(c,e[f],d&&d[f],a)}};var Ea=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Fa=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var Q=function(a){this.s=this.K=this.D="";this.M=null;this.J=this.i="";this.h=this.fa=!1;if(a instanceof Q){this.h=a.h;Ga(this,a.D);var b=a.K;R(this);this.K=b;b=a.s;R(this);this.s=b;Ha(this,a.M);b=a.i;R(this);this.i=b;Ia(this,a.l.clone());a=a.J;R(this);this.J=a}else a&&(b=String(a).match(Ea))?(this.h=!1,Ga(this,b[1]||"",!0),a=b[2]||"",R(this),this.K=S(a),a=b[3]||"",R(this),this.s=S(a,!0),Ha(this,b[4]),a=b[5]||"",R(this),this.i=S(a,!0),Ia(this,b[6]||"",!0),a=b[7]||"",R(this),this.J=S(a)):(this.h=!1,
this.l=new W(null,this.h))};Q.prototype.toString=function(){var a=[],b=this.D;b&&a.push(X(b,Ja,!0),":");var c=this.s;if(c||"file"==b)a.push("//"),(b=this.K)&&a.push(X(b,Ja,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.M,null!=c&&a.push(":",String(c));if(c=this.i)this.s&&"/"!=c.charAt(0)&&a.push("/"),a.push(X(c,"/"==c.charAt(0)?Ka:La,!0));(c=this.l.toString())&&a.push("?",c);(c=this.J)&&a.push("#",X(c,Ma));return a.join("")};
Q.prototype.resolve=function(a){var b=this.clone(),c=!!a.D;c?Ga(b,a.D):c=!!a.K;if(c){var d=a.K;R(b);b.K=d}else c=!!a.s;c?(d=a.s,R(b),b.s=d):c=null!=a.M;d=a.i;if(c)Ha(b,a.M);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.s&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],f=0;f<e.length;){var h=e[f++];"."==h?d&&f==e.length&&k.push(""):".."==
h?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),d&&f==e.length&&k.push("")):(k.push(h),d=!0)}d=k.join("/")}else d=e}c?(R(b),b.i=d):c=""!==a.l.toString();c?Ia(b,a.l.clone()):c=!!a.J;c&&(a=a.J,R(b),b.J=a);return b};Q.prototype.clone=function(){return new Q(this)};
var Ga=function(a,b,c){R(a);a.D=c?S(b,!0):b;a.D&&(a.D=a.D.replace(/:$/,""))},Ha=function(a,b){R(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.M=b}else a.M=null},Ia=function(a,b,c){R(a);b instanceof W?(a.l=b,a.l.V(a.h)):(c||(b=X(b,Na)),a.l=new W(b,a.h))};Q.prototype.getQuery=function(){return this.l.toString()};Q.prototype.removeParameter=function(a){R(this);this.l.remove(a);return this};var R=function(a){if(a.fa)throw Error("Tried to modify a read-only Uri");};
Q.prototype.V=function(a){this.h=a;this.l&&this.l.V(a)};
var S=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},X=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Oa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Oa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ja=/[#\/\?@]/g,La=/[#\?:]/g,Ka=/[#\?]/g,Na=/[#\?@]/g,Ma=/#/g,W=function(a,b){this.b=this.a=null;this.f=a||null;this.h=!!b},Y=function(a){a.a||(a.a=new K,a.b=0,a.f&&Fa(a.f,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};q=W.prototype;q.add=function(a,b){Y(this);this.f=null;a=Z(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b=J(this.b)+1;return this};q.remove=function(a){Y(this);a=Z(this,a);return this.a.O(a)?(this.f=null,this.b=J(this.b)-this.a.get(a).length,this.a.remove(a)):!1};q.clear=function(){this.a=this.f=null;this.b=0};q.O=function(a){Y(this);a=Z(this,a);return this.a.O(a)};
q.forEach=function(a,b){Y(this);this.a.forEach(function(c,d){xa(c,function(e){a.call(b,e,d,this)},this)},this)};q.C=function(){Y(this);for(var a=this.a.m(),b=this.a.C(),c=[],d=0;d<b.length;d++)for(var e=a[d],k=0;k<e.length;k++)c.push(b[d]);return c};q.m=function(a){Y(this);var b=[];if("string"===typeof a)this.O(a)&&(b=ya(b,this.a.get(Z(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=ya(b,a[c])}return b};
q.set=function(a,b){Y(this);this.f=null;a=Z(this,a);this.O(a)&&(this.b=J(this.b)-this.a.get(a).length);this.a.set(a,[b]);this.b=J(this.b)+1;return this};q.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};
q.toString=function(){if(this.f)return this.f;if(!this.a)return"";for(var a=[],b=this.a.C(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var k=0;k<d.length;k++){var f=e;""!==d[k]&&(f+="="+encodeURIComponent(String(d[k])));a.push(f)}}return this.f=a.join("&")};q.clone=function(){var a=new W;a.f=this.f;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};var Z=function(a,b){b=String(b);a.h&&(b=b.toLowerCase());return b};
W.prototype.V=function(a){a&&!this.h&&(Y(this),this.f=null,this.a.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.f=null,this.a.set(Z(this,d),za(b)),this.b=J(this.b)+b.length))},this));this.h=a};W.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Da(arguments[b],function(c,d){this.add(d,c)},this)};var Pa=new E;
(function(a,b,c,d,e,k,f,h){function n(){if(b.app.getDetails){var g=b.app.getDetails();if(g&&g.version)return g.version}return"0"}function r(g){e.remove(x).finally(function(){ra(a);D(f);g&&g()})}function w(g,m){if("active"===g||"warning"===g)k.setIcon({path:{16:"active_16.png",32:"active_32.png"},tabId:m}),"active"!==g&&(k.setBadgeText({text:"!",tabId:m}),k.setBadgeBackgroundColor({color:"#a142f4",tabId:m}));else if("inactive"===g||"error"===g)k.setIcon({path:{16:"inactive_16.png",32:"inactive_32.png"},tabId:m}),
"inactive"!==g&&(k.setBadgeText({text:"!",tabId:m}),k.setBadgeBackgroundColor({color:"#a142f4",tabId:m}))}function G(g){d.sendMessage(g,{command:"getPreviewStatusInfo"},function(m){if(m&&m.isInPreview){var p=m.containerPublicId,l=m.expCookie;p&&e.get("previewData").then(function(t){t=t.previewData;t&&t[p]?t&&t[p]&&t[p].expCookie!==l&&(d.sendMessage(g,{command:"setPreviewStatus",previewStatus:2}),w("warning",g)):(d.sendMessage(g,{command:"setPreviewStatus",previewStatus:2}),w("warning",g))})}})}var x=
"host token modelUrl editorTab authUser checkRedirect deviceType language containerParams".split(" ");c.onMessageExternal.addListener(function(g,m,p){var l={success:!1,version:n()};if("set"===g.command){var t={host:g.host,token:g.token,modelUrl:g.modelUrl,authUser:g.authUser,deviceType:g.deviceType,language:g.language,editorTab:m.tab.id,checkRedirect:!0};if(g.containerPublicId){var ta={containerPublicId:g.containerPublicId,experiment:"edit",tabId:m.tab.id,startTimeMs:h()};pa(f,ta);t.containerParams=
ta}ua(a,m.tab.id,g.deviceType);e.set(t).then(function(){l.success=!0;p(l)},function(){l.success=!1;p(l)});return!0}if("reset"===g.command)return r(function(){l.success=!c.lastError;p(l)}),!0;if("getVersion"===g.command)l.success=!0,p(l);else{if("removeIdFromPreview"===g.command){var ea=g.containerPublicId;e.get("previewData","containerParams").then(function(u){var N;u.previewData&&u.previewData[ea]&&(delete u.previewData[ea],e.set(u).catch(function(O){console.log(O)}));(null===(N=u.containerParams)||
void 0===N?void 0:N.containerPublicId)===ea&&(D(f),e.remove(["containerParams"]))}).finally(function(){l.success=!0;p(l)});return!0}if("preview"===g.command){t=g.enterDebugModeUrl;var T=g.deviceType;if("web"===T||C[T])if(/^https?:\/\//i.test(t)){var fa=g.containerPublicId,U=void 0;g.auth&&(U={containerPublicId:fa,resourceKey:g.resourceKey,auth:g.auth,experiment:g.expCookie,debug:g.debugMode?"x":void 0,startTimeMs:h(),modelUrl:t},pa(f,U));d.create({url:t},function(u){var N=(new Q(m.url)).resolve(new Q("/")).toString();
e.get("previewData").catch(function(){return{previewData:{}}}).then(function(O){O=O.previewData;var P={};P=(P[fa]={containerName:g.containerName,experimentName:g.experimentName,variationName:g.variationName,expCookie:g.expCookie,endPreviewUrl:g.endPreviewUrl,debugMode:g.debugMode,livePreview:g.livePreview},P);var V={host:N,previewTab:u.id,containerPublicId:fa};U?(V.previewData=P,V.containerParams=U):(V.previewData=Object.assign(Object.assign({},O),P),e.remove(["containerParams"]));e.set(V).catch(function(Qa){console.log(Qa)})});
"web"!==T&&qa(a,u.id,T)});l.success=!0}else l.error="nonAllowedScheme";else l.error="invalidDevice";p(l)}else"getContainerParams"===g.command?e.get("containerParams").catch(function(){return{}}).then(function(u){(u=u.containerParams)&&144E5>h()-u.startTimeMs&&(void 0===u.tabId||u.tabId===m.tab.id)?(u={version:n(),containerPublicId:u.containerPublicId,resourceKey:u.resourceKey,experimentCookie:u.experiment,debug:u.debug,success:!0},p(u)):(l.success=!0,p(l))}):p(l)}return!1});c.onMessage.addListener(function(g,
m,p){if("get"===g.command)return e.get.apply(e,ba(x.concat(["previewTab","containerPublicId"]))).then(function(l){var t=new Q(m.url);0===m.url.indexOf(l.host)&&"/optimize/opt-launch.html"===t.i||"/opt_clear_cache"===t.i?p({success:!0}):l.editorTab===m.tab.id?p({success:!0,token:l.token,modelUrl:l.modelUrl||"",authUser:l.authUser||"",checkRedirect:l.checkRedirect,deviceType:l.deviceType,language:l.language||"",host:l.host||"https://www.google.com/",editorTab:m.tab.id}):g.isFrame||l.previewTab!==m.tab.id?
p({success:!0}):(l={success:!0,containerPublicId:l.containerPublicId},e.remove(["previewTab","containerPublicId"]),p(l))}).catch(function(){p({success:!1})}),!0;"setIcon"===g.command?w(g.iconState,m.tab.id):"endPreview"===g.command?e.get("containerParams").then(function(l){var t;(null===(t=l.containerParams)||void 0===t?void 0:t.containerPublicId)===g.containerPublicId&&(e.remove(["containerParams"]),D(f))}):p({success:!1});return!1});d.onRemoved.addListener(function(g){e.get("editorTab").then(function(m){(m=
m.editorTab)&&m===g&&r()})});d.onUpdated.addListener(function(g,m){e.get("editorTab","modelUrl","checkRedirect").then(function(p){var l;if(l=p.editorTab&&p.editorTab===g&&!p.checkRedirect&&"loading"===m.status&&m.url)l=p.modelUrl,p=ma(m.url),l=ma(l),l=!(p&&l&&p===l);l&&r()})});d.onActivated.addListener(function(g){G(g.tabId)})})(new function(){var a=chrome.i18n,b=chrome.webRequest,c=chrome.debugger;this.runtime=chrome.runtime;this.i18n=a;this.webRequest=b;this.I=c;this.g=null},chrome,chrome.runtime,
chrome.tabs,Pa,chrome.browserAction,function(a){return new na(a,function(){return(new Date).getTime()})}(Pa),function(){return(new Date).getTime()});
