/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h,m=this||self,p=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},q=function(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length},t=function(a,b){function c(){}c.prototype=b.prototype;a.ja=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ha=function(d,e,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[e].apply(d,g)}},u=function(a){return a};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}t(x,Error);x.prototype.name="CustomError";var y=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");x.call(this,c+a[d])};t(y,x);y.prototype.name="AssertionError";
var z=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new y(""+e,f||[]);},A=function(a,b,c){a||z("",null,b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b){throw new y("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},C=function(a,b,c){"number"!==typeof a&&z("Expected number but got %s: %s.",[p(a),a],b,Array.prototype.slice.call(arguments,2));return a},aa=function(a,b,c){"string"!==typeof a&&z("Expected string but got %s: %s.",
[p(a),a],b,Array.prototype.slice.call(arguments,2))};var ba=Array.prototype.forEach?function(a,b,c){A(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function ca(a){return Array.prototype.concat.apply([],arguments)}function da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ma=function(a,b){if(b)a=a.replace(ea,"&amp;").replace(fa,"&lt;").replace(ha,"&gt;").replace(ia,"&quot;").replace(ja,"&#39;").replace(ka,"&#0;");else{if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ea,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(fa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ha,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ia,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ja,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ka,"&#0;"))}return a},ea=/&/g,fa=/</g,ha=/>/g,ia=/"/g,ja=/'/g,
ka=/\x00/g,la=/[\x00&<>"']/;var D;var F=function(a,b){this.V=a===E&&b||"";this.ca=na};F.prototype.aa=!0;F.prototype.Z=function(){return this.V};F.prototype.toString=function(){return"Const{"+this.V+"}"};var oa=function(a){if(a instanceof F&&a.constructor===F&&a.ca===na)return a.V;B("expected object of type Const, got '"+a+"'");return"type_error:Const"},na={},E={};var H=function(a,b,c){this.T=c===G?a:"";this.X=b};H.prototype.ea=!0;H.prototype.aa=!0;H.prototype.Z=function(){return this.T.toString()};H.prototype.toString=function(){return"SafeHtml{"+this.T+"}"};
var pa=function(a){if(a instanceof H&&a.constructor===H)return a.T;B("expected object of type SafeHtml, got '"+a+"' of type "+p(a));return"type_error:SafeHtml"},ra=function(a){if(a instanceof H)return a;var b="object"==typeof a,c=null;b&&a.ea&&(c=a.X);return qa(ma(b&&a.aa?a.Z():String(a)),c)},G={},qa=function(a,b){if(void 0===D){var c=null;var d=m.trustedTypes;if(d&&d.createPolicy)try{c=d.createPolicy("goog#html",{createHTML:u,createScript:u,createScriptURL:u})}catch(e){m.console&&m.console.error(e.message)}D=
c}a=(c=D)?c.createHTML(a):a;return new H(a,b,G)},sa=new H(m.trustedTypes&&m.trustedTypes.emptyHTML||"",0,G);var ta=function(a,b,c){aa(oa(a),"must provide justification");A(!/^[\s\xa0]*$/.test(oa(a)),"must provide non-empty justification");return qa(b,c||null)};var ua={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},va=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=pa(sa);return!b.parentElement}),wa=function(a,b){if(va())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=pa(b)};var za=function(a){return-1!=a.indexOf("&")?"document"in m?xa(a):ya(a):a},xa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=m.document.createElement("div");return a.replace(Aa,function(d,e){var f=b[d];if(f)return f;"#"==e.charAt(0)&&(e=Number("0"+e.substr(1)),isNaN(e)||(f=String.fromCharCode(e)));if(!f){f=ta(new F(E,"Single HTML entity."),d+" ");if(c.tagName&&ua[c.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+c.tagName+
".");wa(c,f);f=c.firstChild.nodeValue.slice(0,-1)}return b[d]=f})},ya=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return"#"!=c.charAt(0)||(c=Number("0"+c.substr(1)),isNaN(c))?b:String.fromCharCode(c)}})},Aa=/&([^;\s<&]+);?/g;var Ba="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},Ca=function(){};Ca.prototype.next=function(){throw Ba;};Ca.prototype.da=function(){return this};var I=function(a,b){this.j={};this.c=[];this.O=this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=I.prototype;h.Y=function(){return this.a};h.l=function(){K(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};h.C=function(){K(this);return this.c.concat()};h.L=function(a){return L(this.j,a)};
h.equals=function(a,b){if(this===a)return!0;if(this.a!=a.Y())return!1;b=b||Da;K(this);for(var c,d=0;c=this.c[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var Da=function(a,b){return a===b};I.prototype.clear=function(){this.j={};this.O=this.a=this.c.length=0};I.prototype.remove=function(a){return L(this.j,a)?(delete this.j[a],this.a--,this.O++,this.c.length>2*this.a&&K(this),!0):!1};
var K=function(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];L(a.j,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){var e={};for(c=b=0;b<a.c.length;)d=a.c[b],L(e,d)||(a.c[c++]=d,e[d]=1),b++;a.c.length=c}};h=I.prototype;h.get=function(a,b){return L(this.j,a)?this.j[a]:b};h.set=function(a,b){L(this.j,a)||(this.a++,this.c.push(a),this.O++);this.j[a]=b};
h.addAll=function(a){if(a instanceof I)for(var b=a.C(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new I(this)};h.toObject=function(){K(this);for(var a={},b=0;b<this.c.length;b++){var c=this.c[b];a[c]=this.j[c]}return a};
h.da=function(a){K(this);var b=0,c=this.O,d=this,e=new Ca;e.next=function(){if(c!=d.O)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw Ba;var f=d.c[b++];return a?f:d.j[f]};return e};var L=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Ea=function(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(q(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Fa=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(q(a)||"string"===typeof a)ba(a,b,c);else{if(a.C&&"function"==typeof a.C)var d=a.C();else if(a.l&&"function"==typeof a.l)d=void 0;else if(q(a)||"string"===typeof a){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=
[],e=0,a)d[e++]=f;e=Ea(a);f=e.length;for(var g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var Ha=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Ia=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var M=function(a,b){this.A=this.H=this.F="";this.K=null;this.G=this.o="";this.i=this.fa=!1;if(a instanceof M){this.i=void 0!==b?b:a.i;Ja(this,a.F);var c=a.H;N(this);this.H=c;c=a.A;N(this);this.A=c;Ka(this,a.K);c=a.o;N(this);this.o=c;La(this,a.f.clone());a=a.G;N(this);this.G=a}else a&&(c=String(a).match(Ha))?(this.i=!!b,Ja(this,c[1]||"",!0),a=c[2]||"",N(this),this.H=O(a),a=c[3]||"",N(this),this.A=O(a,!0),Ka(this,c[4]),a=c[5]||"",N(this),this.o=O(a,!0),La(this,c[6]||"",!0),a=c[7]||"",N(this),this.G=
O(a)):(this.i=!!b,this.f=new P(null,this.i))};M.prototype.toString=function(){var a=[],b=this.F;b&&a.push(Q(b,Ma,!0),":");var c=this.A;if(c||"file"==b)a.push("//"),(b=this.H)&&a.push(Q(b,Ma,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.K,null!=c&&a.push(":",String(c));if(c=this.o)this.A&&"/"!=c.charAt(0)&&a.push("/"),a.push(Q(c,"/"==c.charAt(0)?Na:Oa,!0));(c=this.f.toString())&&a.push("?",c);(c=this.G)&&a.push("#",Q(c,Pa));return a.join("")};
M.prototype.resolve=function(a){var b=this.clone(),c=!!a.F;c?Ja(b,a.F):c=!!a.H;if(c){var d=a.H;N(b);b.H=d}else c=!!a.A;c?(d=a.A,N(b),b.A=d):c=null!=a.K;d=a.o;if(c)Ka(b,a.K);else if(c=!!a.o){if("/"!=d.charAt(0))if(this.A&&!this.o)d="/"+d;else{var e=b.o.lastIndexOf("/");-1!=e&&(d=b.o.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var l=e[g++];"."==l?d&&g==e.length&&f.push(""):".."==
l?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(l),d=!0)}d=f.join("/")}else d=e}c?(N(b),b.o=d):c=""!==a.f.toString();c?La(b,a.f.clone()):c=!!a.G;c&&(a=a.G,N(b),b.G=a);return b};M.prototype.clone=function(){return new M(this)};
var Ja=function(a,b,c){N(a);a.F=c?O(b,!0):b;a.F&&(a.F=a.F.replace(/:$/,""))},Ka=function(a,b){N(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.K=b}else a.K=null},La=function(a,b,c){N(a);b instanceof P?(a.f=b,a.f.U(a.i)):(c||(b=Q(b,Qa)),a.f=new P(b,a.i))};M.prototype.getQuery=function(){return this.f.toString()};M.prototype.removeParameter=function(a){N(this);this.f.remove(a);return this};var N=function(a){if(a.fa)throw Error("Tried to modify a read-only Uri");};
M.prototype.U=function(a){this.i=a;this.f&&this.f.U(a)};
var O=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Q=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ra),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ra=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ma=/[#\/\?@]/g,Oa=/[#\?:]/g,Na=/[#\?]/g,Qa=/[#\?@]/g,Pa=/#/g,P=function(a,b){this.a=this.b=null;this.g=a||null;this.i=!!b},R=function(a){a.b||(a.b=new I,a.a=0,a.g&&Ia(a.g,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=P.prototype;h.Y=function(){R(this);return this.a};h.add=function(a,b){R(this);this.g=null;a=S(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a=C(this.a)+1;return this};h.remove=function(a){R(this);a=S(this,a);return this.b.L(a)?(this.g=null,this.a=C(this.a)-this.b.get(a).length,this.b.remove(a)):!1};h.clear=function(){this.b=this.g=null;this.a=0};h.L=function(a){R(this);a=S(this,a);return this.b.L(a)};
h.forEach=function(a,b){R(this);this.b.forEach(function(c,d){ba(c,function(e){a.call(b,e,d,this)},this)},this)};h.C=function(){R(this);for(var a=this.b.l(),b=this.b.C(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.l=function(a){R(this);var b=[];if("string"===typeof a)this.L(a)&&(b=ca(b,this.b.get(S(this,a))));else{a=this.b.l();for(var c=0;c<a.length;c++)b=ca(b,a[c])}return b};
h.set=function(a,b){R(this);this.g=null;a=S(this,a);this.L(a)&&(this.a=C(this.a)-this.b.get(a).length);this.b.set(a,[b]);this.a=C(this.a)+1;return this};h.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.g)return this.g;if(!this.b)return"";for(var a=[],b=this.b.C(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.g=a.join("&")};h.clone=function(){var a=new P;a.g=this.g;this.b&&(a.b=this.b.clone(),a.a=this.a);return a};var S=function(a,b){b=String(b);a.i&&(b=b.toLowerCase());return b};
P.prototype.U=function(a){a&&!this.i&&(R(this),this.g=null,this.b.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.g=null,this.b.set(S(this,d),da(b)),this.a=C(this.a)+b.length))},this));this.i=a};P.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Fa(arguments[b],function(c,d){this.add(d,c)},this)};var Sa={ia:!0},T=function(){throw Error("Do not instantiate directly");};T.prototype.R=null;T.prototype.getContent=function(){return this.content};T.prototype.toString=function(){return this.content};var U=function(){T.call(this)};t(U,T);U.prototype.W=Sa;var Ta=function(a){var b=null!=a&&a.W===Sa;b&&A(a.constructor===U);return b};var Ua=function(a){if(null!=a)switch(a.R){case 1:return 1;case -1:return-1;case 0:return 0}return null},Xa=function(a){return Ta(a)?a:a instanceof H?Va(pa(a).toString(),a.X):Va(Wa(String(a)),Ua(a))},Va=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.R=d);return c}}(U),V=function(a){return Ta(a)?String(String(a.getContent()).replace(Ya,"").replace(Za,"&lt;")).replace($a,ab):Wa(a)},Wa=function(a){a=String(a);return a=ma(a,void 0)},
bb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},ab=function(a){return bb[a]},$a=/[\x00\x22\x27\x3c\x3e]/g,Ya=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Za=/</g;var W=function(a,b){this.text=a;this.type=b},cb=function(a,b){this.spans=a;this.type=b},db="break case catch continue debugger default delete do else finally for function if in instanceof new return switch this throw try typeof var void while with false null undefined true abstract boolean byte char const double final float goto int long native short synchronized throws transient volatile class enum export extends import super implements interface let package private protected public static yield".split(" "),
eb=function(a,b){try{var c=new XMLHttpRequest;c.open("GET",a,!0);var d=!1;c.onreadystatechange=function(){d||4!=c.readyState||200!=c.status||(d=!0,b(c))};c.send()}catch(e){}},X={type:"html-tag",open:/^<\/?([-_a-zA-Z0-9]+)/,close:/^(\/?)>/,ba:function(a,b){a.S=b[1].toUpperCase();return!0},P:function(a,b){""==b[1]&&("SCRIPT"==a.S?(a.v="js-code",a.J=null,a.N=fb):"STYLE"==a.S&&(a.v="css-code",a.J=null,a.N=gb));return!0}},hb=[{type:"html-comment",open:"\x3c!--",close:"--\x3e"},{type:"html-cdata",open:"<![CDATA[",
close:"]]\x3e"},{type:"html-doctype",open:"<!",close:">"},X,{type:"html-attribute-url",open:/^"(https?|\/\/)/,close:'"',escape:"\\",u:X},{type:"html-attribute-url",open:/^'(https?|\/\/)/,close:"'",escape:"\\",u:X},{type:"html-attribute-value",open:'"',close:'"',escape:"\\",u:X},{type:"html-attribute-value",open:"'",close:"'",escape:"\\",u:X},{type:"html-attribute-name",open:/(^[-_a-zA-Z0-9]+)/,close:"=",u:X}],fb=[{type:"js-comment",open:"//",I:!0},{type:"js-comment",open:"/*",close:"*/"},{type:"js-string",
open:'"',close:'"',escape:"\\",I:!0},{type:"js-regex",open:"/",close:"/",escape:"\\",I:!0},{open:/^\.[a-zA-Z_][a-zA-Z_0-9]*/,B:!0},{type:"js-keyword",open:/^[a-zA-Z_][a-zA-Z_0-9]*/,ba:function(a,b){return 0<=db.indexOf(b[0])},B:!0},{open:/^[a-zA-Z_][a-zA-Z_0-9.]*/,B:!0},{type:"js-number",open:/^[+-]?[0-9.]+/,B:!0},{type:"js-string",open:"'",close:"'",escape:"\\",I:!0},{type:"html-tag",open:/^\s*<\/script/,close:/>/,P:function(a){a.v=null;a.J=null;a.N=hb;return!0}}],ib={open:"{",close:"}"},Y={open:":",
close:";",u:ib},gb=[{type:"css-comment",open:"\x3c!--",close:">"},{type:"css-comment",open:"/*",close:"*/"},{type:"css-string",open:'"',close:'"',escape:"\\",I:!0},{type:"css-number",open:/^[+-]?[0-9.]+[a-zA-Z]*/,B:!0,u:Y},{type:"css-color",open:/^#[0-9a-zA-Z]{3}[0-9a-zA-Z]{0,3}/,B:!0,u:Y},ib,Y,{type:"css-name",open:/^[-.#_a-zA-Z0-9]+/,B:!0,u:ib},{type:"css-attribute-value",open:/^[-a-zA-Z_0-9]+/,B:!0,u:Y},{type:"css-string",open:"'",close:"'",escape:"\\",I:!0},{type:"html-tag",open:/^\s*<\/style/,
close:/>/,P:function(a){a.N=hb;a.v=null;a.J=null;return!0}}],kb=function(a){var b={N:hb,S:null,J:null,v:null},c=[],d=[null],e=[null],f=void 0;a=za(a);a.split("\n").forEach(function(g){var l=[],n=0;b.J=b.v;for(var k=0,J=g.length;k<J;k+=w?0:1){var w=!1;if(!f||f.escape!=g.charAt(k)){if(f){var v=f.close?jb(b,f.close,g,k,f.P):0;v&&(k+=v,l.push(new W(g.substring(n,k),f.type||b.v)),n=k,d.pop(),e.pop(),f=e[e.length-1],w=!0)}for(var Ga=0,r;!w&&(r=b.N[Ga]);Ga++)r.u==f&&(v=jb(b,r.open,g,k,r.ba))&&(k>n&&r.type!=
d[d.length-1]&&(l.push(new W(g.substring(n,k),d[d.length-1]||b.v)),n=k),k+=v,r.B?(l.push(new W(g.substring(n,k),r.type||b.v)),n=k):(d.push(r.type),e.push(r),f=r),w=!0)}}n<J&&l.push(new W(g.substring(n,J),d[d.length-1]||b.v));c.push(new cb(l,b.J));f&&f.I&&(d.pop(),e.pop(),f=e[e.length-1])});return c},jb=function(a,b,c,d,e){var f;return b.exec&&(f=b.exec(c.substring(d)))?e&&!e(a,f)?0:f[0].length:c.substring(d,d+b.length)==b?b.length:0};var Z,lb=document.location.href;Z=lb instanceof M?lb.clone():new M(lb,void 0);
(function(a,b,c){eb(a,function(d){var e=document.getElementById("source");d=kb(d.response+"");for(var f=c||1,g='<div class="header"><h1 id="title">Source: '+Xa(a)+"</h1>"+(a?'<a id="view-source" href="view-source:'+V(a)+"\">View Source in Chrome's Source code viewer</a>":"")+'</div><div class="line-gutter-backdrop"></div><table><tbody>',l=d.length,n=0;n<l;n++){var k=d[n];g+="<tr"+(k.type?' class="'+V(k.type)+'"':"")+'><td class="line-number'+(n+1>=b&&n+1<=b+f?" highlight":"")+'" data-value="'+V(n+
1)+'"></td><td class="line-content">';k=k.spans;for(var J=k.length,w=0;w<J;w++){var v=k[w];g+=v.type?'<span class="'+V(v.type)+'">'+Xa(v.text)+"</span>":Xa(v.text)}g+="</td></tr>"}d=Va(g+"</tbody></table>");f=typeof d;if("object"==f&&null!=d||"function"==f)if(d instanceof T){if(d.W!==Sa)throw Error("Sanitized content was not of kind HTML.");d=ta(new F(E,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value."),d.toString(),d.R)}else B("Soy template output is unsafe for use as HTML: "+
d),d=ra("zSoyz");else d=ra(String(d));wa(A(e),d);e=b||0;d=0;f=document;f=f.querySelectorAll&&f.querySelector?f.querySelectorAll("TR"):f.getElementsByTagName("TR");0<=e&&e<f.length&&(d=f[e].offsetTop);window.scrollTo(0,d)})})(Z.f.get("url")||"",parseInt(Z.f.get("line")||-1,10),parseInt(Z.f.get("count")||0,10));
